### ISSUE TITLE
Placing signs crashes if the cursor location is above 0

### ISSUE THREAD

**Issue by janno288** [OldHaven-Network/MegaMod-Mixins#21]
My fellow comrade Zetar99 exprieces a crash while writing a sign.
ERROR LOG:
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    at java.lang.String.substring(Unknown Source)
    at po.redirect$zzd000$redirect2(SourceFile:518)
    at po.a(SourceFile:58)
    at po.a(SourceFile:9)
    at ll.a(SourceFile:94)
    at yc.a(SourceFile:96)
    at px.b(EntityRenderer.java:648)
    at net.minecraft.client.Minecraft.run(SourceFile:781)
    at java.lang.Thread.run(Unknown Source)

**Comment by ScarletLovell** [comment]
I instantly know what this one is. Will fix ASAP

**Comment by ScarletLovell** [comment]
Fixed with https://github.com/OldHaven-Network/MegaMod-Mixins/pull/22
