### ISSUE TITLE
Chat cursor can go under 0, causing a crash

### ISSUE THREAD

**Issue by janno288** [OldHaven-Network/MegaMod-Mixins#24]
While formating/editin text in chat my game sadly crashed
ERROR LOG:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at gc.redirect$zzk000$redirect1(SourceFile:593)
	at gc.a(SourceFile:41)
	at da.g(SourceFile:134)
	at da.e(SourceFile:112)
	at net.minecraft.client.Minecraft.k(SourceFile:1299)
	at net.minecraft.client.Minecraft.run(SourceFile:754)
	at java.lang.Thread.run(Unknown Source)

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/598ddf2378b688581f384aaa9e112ffd6347fd80
