### ISSUE TITLE
MegaMod's WAILA makes the game crash if you look at dungeon bricks from Aether.

### ISSUE THREAD

**Issue by ghost** [OldHaven-Network/MegaMod-Mixins#26]
java.lang.NullPointerException
    at iz.b(ItemStack.java:72)
    at bb.a(RenderItem.java:187)
    at uq.guiWAILA(GuiIngame.java:704)
    at uq.handler$zzn000$renderGameOverlay_Text(GuiIngame.java:610)
    at uq.a(GuiIngame.java:179)
    at px.b(EntityRenderer.java:450)
    at EntityRendererProxy.b(EntityRendererProxy.java:23)
    at net.minecraft.client.Minecraft.run(Minecraft.java:516)
    at java.lang.Thread.run(Thread.java:748)

**Comment by ScarletLovell** [comment]
Won't fix for now. may re-open in the future
