### ISSUE TITLE
multiplayer menu bug/crash

### ISSUE THREAD

**Issue by janno288** [OldHaven-Network/MegaMod-Mixins#28]
Editing a server in the multiplayer menu and then clicking done crashes the game for me
ERROR LOG:
java.lang.NullPointerException
	at net.oldhaven.gui.multiplayer.GuiMultiplayerEditServer.a(GuiMultiplayerEditServer.java:81)
	at da.a(SourceFile:72)
	at net.oldhaven.gui.multiplayer.GuiMultiplayerEditServer.a(GuiMultiplayerEditServer.java:100)
	at da.f(SourceFile:120)
	at da.e(SourceFile:108)
	at net.minecraft.client.Minecraft.k(SourceFile:1299)
	at net.minecraft.client.Minecraft.run(SourceFile:754)
	at java.lang.Thread.run(Unknown Source

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/598ddf2378b688581f384aaa9e112ffd6347fd80
