### ISSUE TITLE
Typing same lines in chat crashes the game

### ISSUE THREAD

**Issue by janno288** [OldHaven-Network/MegaMod-Mixins#29]
I Typed this
Ashleez_ = ADMIN
**PRESSED UP ARROW on KEYBOARD**
_0creeper0_ = ADMIn
**PRESSED UP ARROW on KEYBOARD**
Blockteen = ADMIN [ENTER]
GAME FROZE AND CRASHED

ERROR LOG:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at gc.redirect$zzk000$redirect1(SourceFile:593)
        at gc.a(SourceFile:41)
        at da.g(SourceFile:134)
        at da.e(SourceFile:112)
        at net.minecraft.client.Minecraft.k(SourceFile:1299)
        at net.minecraft.client.Minecraft.run(SourceFile:754)
        at java.lang.Thread.run(Unknown Source)

**Comment by ScarletLovell** [comment]
Possibly fixed in Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/598ddf2378b688581f384aaa9e112ffd6347fd80

**Comment by ScarletLovell** [comment]
Didn't mean to add those. rip. Closing this issue for now.
