### ISSUE TITLE
Writing too soon after placing a sign crashes the game

### ISSUE THREAD

**Issue by D3JF** [OldHaven-Network/MegaMod-Mixins#30]
This still seems to be occuring in version 0.5.1.1.

**Crash log:**
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963)
	at yc.redirect$zzm000$redirect3(SourceFile:593)
	at yc.a(SourceFile:60)
	at da.g(SourceFile:134)
	at da.e(SourceFile:112)
	at net.minecraft.client.Minecraft.k(SourceFile:1299)
	at net.minecraft.client.Minecraft.run(SourceFile:754)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/4d689d56a505d4459f905a6a8ea8581acf499f56
