### ISSUE TITLE
Crash on MultiMC due to missing DiscordRPC jar.

### ISSUE THREAD

**Issue by SolDev69** [OldHaven-Network/MegaMod-Mixins#44]
Here is the log. Game crashes due to missing DiscordRPC.jar after compiling from github and adding the jar to multimc.

MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/user/Desktop/MultiMC/instances/multimc-fabric-b1.7.3/.minecraft

Java path is:
C:/Program Files/AdoptOpenJDK/jdk-8.0.242.08-hotspot/bin/javaw.exe

Java is version 1.8.0_242, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/user/Desktop/MultiMC/instances/multimc-fabric-b1.7.3/natives

Traits:
traits noapplet
traits texturepacks
traits legacyLaunch

Libraries:
  C:/Users/user/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/user/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/user/Desktop/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  C:/Users/user/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar
  C:/Users/user/Desktop/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.2.64/tiny-remapper-0.2.2.64.jar
  C:/Users/user/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/user/Desktop/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/ow2/asm/asm/8.0/asm-8.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/8.0/asm-analysis-8.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/8.0/asm-commons-8.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/8.0/asm-tree-8.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/8.0/asm-util-8.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader/0.8.2+build.194/fabric-loader-0.8.2+build.194.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/user/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/user/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/user/Desktop/MultiMC/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  C:/Users/user/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/user/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] MegaMod-Mixins

Params:
  --username  --session  --gameDir C:/Users/user/Desktop/MultiMC/instances/multimc-fabric-b1.7.3/.minecraft --assetsDir C:/Users/user/Desktop/MultiMC/instances/multimc-fabric-b1.7.3/.minecraft/resources

Window size: 854 x 480

Java Arguments:
[-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms128m, -Xmx16384m, -Duser.language=en]

Minecraft process ID: 21772

Listening for transport dt_socket at address: 5005
Using onesix launcher.

Could not find Minecraft path field.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
stone 1
grass 2
dirt 3
stonebrick 4
wood 5
sapling 6
bedrock 7
water 8
water 9
lava 10
lava 11
sand 12
gravel 13
oreGold 14
oreIron 15
oreCoal 16
log 17
leaves 18
sponge 19
glass 20
oreLapis 21
blockLapis 22
dispenser 23
sandStone 24
musicBlock 25
bed 26
goldenRail 27
detectorRail 28
pistonStickyBase 29
web 30
tallgrass 31
deadbush 32
pistonBase 33
cloth 35
flower 37
rose 38
mushroom 39
mushroom 40
blockGold 41
blockIron 42
stoneSlab 43
stoneSlab 44
brick 45
tnt 46
bookshelf 47
stoneMoss 48
obsidian 49
torch 50
fire 51
mobSpawner 52
stairsWood 53
chest 54
redstoneDust 55
oreDiamond 56
blockDiamond 57
workbench 58
crops 59
farmland 60
furnace 61
furnace 62
sign 63
doorWood 64
ladder 65
rail 66
stairsStone 67
sign 68
lever 69
pressurePlate 70
doorIron 71
pressurePlate 72
oreRedstone 73
oreRedstone 74
notGate 75
notGate 76
button 77
snow 78
ice 79
snow 80
cactus 81
clay 82
reeds 83
jukebox 84
fence 85
pumpkin 86
hellrock 87
hellsand 88
lightgem 89
portal 90
litpumpkin 91
cake 92
diode 93
diode 94
lockedchest 95
trapdoor 96
shovelIron 0
pickaxeIron 1
hatchetIron 2
flintAndSteel 3
apple 4
bow 5
arrow 6
coal 7
emerald 8
ingotIron 9
ingotGold 10
swordIron 11
swordWood 12
shovelWood 13
pickaxeWood 14
hatchetWood 15
swordStone 16
shovelStone 17
pickaxeStone 18
hatchetStone 19
swordDiamond 20
shovelDiamond 21
pickaxeDiamond 22
hatchetDiamond 23
stick 24
bowl 25
mushroomStew 26
swordGold 27
shovelGold 28
pickaxeGold 29
hatchetGold 30
string 31
feather 32
sulphur 33
hoeWood 34
hoeStone 35
hoeIron 36
hoeDiamond 37
hoeGold 38
seeds 39
wheat 40
bread 41
helmetCloth 42
chestplateCloth 43
leggingsCloth 44
bootsCloth 45
helmetChain 46
chestplateChain 47
leggingsChain 48
bootsChain 49
helmetIron 50
chestplateIron 51
leggingsIron 52
bootsIron 53
helmetDiamond 54
chestplateDiamond 55
leggingsDiamond 56
bootsDiamond 57
helmetGold 58
chestplateGold 59
leggingsGold 60
bootsGold 61
flint 62
porkchopRaw 63
porkchopCooked 64
painting 65
appleGold 66
sign 67
doorWood 68
bucket 69
bucketWater 70
bucketLava 71
minecart 72
saddle 73
doorIron 74
redstone 75
snowball 76
boat 77
leather 78
milk 79
brick 80
clay 81
reeds 82
paper 83
book 84
slimeball 85
minecartChest 86
minecartFurnace 87
egg 88
compass 89
fishingRod 90
clock 91
yellowDust 92
fishRaw 93
fishCooked 94
dyePowder 95
bone 96
sugar 97
cake 98
bed 99
diode 100
cookie 101
map 102
shears 103
record 2000
record 2001
16 achievements
cloth -221
log -239
stoneSlab -212
sapling -250
leaves -238
151 recipes
Setting user: MicherPlayzMC, token:<ACCESS TOKEN>:<PROFILE ID>
Exception in thread "Minecraft main thread" java.lang.NoClassDefFoundError: club/minnced/discord/rpc/DiscordRPC
	at net.oldhaven.MegaMod.<init>(MegaMod.java:28)
	at net.minecraft.client.Minecraft.handler$zbb000$onRun(SourceFile:2646)
	at net.minecraft.client.Minecraft.a(SourceFile)
	at net.minecraft.client.Minecraft.run(SourceFile:716)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: club.minnced.discord.rpc.DiscordRPC
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 5 more
Clipboard copy at: 02 Dec 2020 12:29:11 -0500

**Comment by ScarletLovell** [comment]
I sadly don't know gradle enough to know how to fix this issue.
At the moment, just copy folders from `club.minnced:java-discord-rpc:2.0.2` into the built jar.
